// <auto-generated />
using System;
using CinemaSystemRandomPlay.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CinemaSystemRandomPlay.Infrastructure.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    [Migration("20260923201318_AddDisposicionSalas")]
    partial class AddDisposicionSalas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CinemaSystemRandomPlay.Domain.Catalogo.Pelicula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Clasificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Peliculas", (string)null);
                });

            modelBuilder.Entity("CinemaSystemRandomPlay.Domain.Funciones.Funcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaHoraInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PeliculaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SalaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PeliculaId");

                    b.HasIndex("SalaId");

                    b.ToTable("Funciones", (string)null);
                });

            modelBuilder.Entity("CinemaSystemRandomPlay.Domain.Funciones.Sala", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.ToTable("Salas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000001"),
                            Nombre = "Sala 1",
                            SucursalId = new Guid("11111111-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            Nombre = "Sala 2",
                            SucursalId = new Guid("11111111-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000003"),
                            Nombre = "Sala 1",
                            SucursalId = new Guid("11111111-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000004"),
                            Nombre = "Sala 1",
                            SucursalId = new Guid("11111111-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("CinemaSystemRandomPlay.Domain.Funciones.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Sucursales", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            Nombre = "Sucursal Centro"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            Nombre = "Sucursal Norte"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            Nombre = "Sucursal Sur"
                        });
                });

            modelBuilder.Entity("CinemaSystemRandomPlay.Domain.Funciones.Funcion", b =>
                {
                    b.HasOne("CinemaSystemRandomPlay.Domain.Catalogo.Pelicula", null)
                        .WithMany()
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaSystemRandomPlay.Domain.Funciones.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("CinemaSystemRandomPlay.Domain.Funciones.Sala", b =>
                {
                    b.HasOne("CinemaSystemRandomPlay.Domain.Funciones.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("CinemaSystemRandomPlay.Domain.Funciones.FilaSala", "Filas", b1 =>
                        {
                            b1.Property<Guid>("SalaId")
                                .HasColumnType("uuid");

                            b1.Property<char>("Letra")
                                .HasColumnType("character(1)");

                            b1.Property<int>("CantidadAsientos")
                                .HasColumnType("integer");

                            b1.HasKey("SalaId", "Letra");

                            b1.ToTable("SalaFilas", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SalaId");

                            b1.HasData(
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000001"),
                                    Letra = 'A',
                                    CantidadAsientos = 12
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000001"),
                                    Letra = 'B',
                                    CantidadAsientos = 12
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000001"),
                                    Letra = 'C',
                                    CantidadAsientos = 12
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000001"),
                                    Letra = 'D',
                                    CantidadAsientos = 12
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000001"),
                                    Letra = 'E',
                                    CantidadAsientos = 12
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000001"),
                                    Letra = 'F',
                                    CantidadAsientos = 12
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000001"),
                                    Letra = 'G',
                                    CantidadAsientos = 12
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000001"),
                                    Letra = 'H',
                                    CantidadAsientos = 12
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000002"),
                                    Letra = 'A',
                                    CantidadAsientos = 8
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000002"),
                                    Letra = 'B',
                                    CantidadAsientos = 10
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000002"),
                                    Letra = 'C',
                                    CantidadAsientos = 12
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000002"),
                                    Letra = 'D',
                                    CantidadAsientos = 12
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000002"),
                                    Letra = 'E',
                                    CantidadAsientos = 14
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000002"),
                                    Letra = 'F',
                                    CantidadAsientos = 14
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000003"),
                                    Letra = 'A',
                                    CantidadAsientos = 10
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000003"),
                                    Letra = 'B',
                                    CantidadAsientos = 10
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000003"),
                                    Letra = 'C',
                                    CantidadAsientos = 10
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000003"),
                                    Letra = 'D',
                                    CantidadAsientos = 10
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000003"),
                                    Letra = 'E',
                                    CantidadAsientos = 10
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000003"),
                                    Letra = 'F',
                                    CantidadAsientos = 10
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000003"),
                                    Letra = 'G',
                                    CantidadAsientos = 10
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000003"),
                                    Letra = 'H',
                                    CantidadAsientos = 10
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000003"),
                                    Letra = 'I',
                                    CantidadAsientos = 10
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000003"),
                                    Letra = 'J',
                                    CantidadAsientos = 10
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000004"),
                                    Letra = 'A',
                                    CantidadAsientos = 8
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000004"),
                                    Letra = 'B',
                                    CantidadAsientos = 8
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000004"),
                                    Letra = 'C',
                                    CantidadAsientos = 8
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000004"),
                                    Letra = 'D',
                                    CantidadAsientos = 8
                                },
                                new
                                {
                                    SalaId = new Guid("22222222-0000-0000-0000-000000000004"),
                                    Letra = 'E',
                                    CantidadAsientos = 8
                                });
                        });

                    b.Navigation("Filas");

                    b.Navigation("Sucursal");
                });
#pragma warning restore 612, 618
        }
    }
}
